# Generated by Django 5.2.8 on 2025-12-01 16:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_authors', models.TextField(blank=True, help_text='Autores favoritos separados por comas')),
                ('favorite_genres', models.TextField(blank=True, help_text='Géneros favoritos separados por comas')),
            ],
            options={
                'db_table': 'library_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True)),
                ('language_code', models.CharField(default='eng', max_length=10)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(default=0)),
                ('text_reviews_count', models.IntegerField(default=0)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'library_books',
                'ordering': ['-average_rating'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='books_search_idx'), models.Index(fields=['publication_year'], name='books_year_idx'), models.Index(fields=['authors'], name='books_authors_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_authors', models.TextField(blank=True)),
                ('preferred_page_range', models.CharField(blank=True, max_length=50)),
                ('min_rating_preference', models.DecimalField(decimal_places=1, default=3.5, max_digits=2)),
                ('total_books_read', models.IntegerField(default=0)),
                ('average_user_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='library_app.user')),
            ],
            options={
                'db_table': 'library_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.user')),
            ],
            options={
                'db_table': 'library_loans',
                'ordering': ['-borrowed_date'],
                'indexes': [models.Index(fields=['user', 'is_returned'], name='library_loa_user_id_a71797_idx'), models.Index(fields=['book', 'is_returned'], name='library_loa_book_id_8758ca_idx'), models.Index(fields=['borrowed_date'], name='library_loa_borrowe_c019e6_idx')],
                'unique_together': {('user', 'book', 'borrowed_date')},
            },
        ),
    ]
