# Generated by Django 5.2.8 on 2025-12-01 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'library_loans',
                'ordering': ['-borrowed_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_authors', models.TextField(blank=True, help_text='Autores favoritos separados por comas')),
                ('favorite_genres', models.TextField(blank=True, help_text='Géneros favoritos separados por comas')),
            ],
            options={
                'db_table': 'library_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_authors', models.TextField(blank=True)),
                ('preferred_page_range', models.CharField(blank=True, max_length=50)),
                ('min_rating_preference', models.DecimalField(decimal_places=1, default=3.5, max_digits=2)),
                ('total_books_read', models.IntegerField(default=0)),
                ('average_user_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'library_user_preferences',
            },
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='books_search_idx',
            old_name='search_vector_idx',
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_id', 'publication_year')},
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='books_year_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['authors'], name='books_authors_idx'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='library_books',
        ),
        migrations.AddField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.book'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.user'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='library_app.user'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrowed_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrowed_date',
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'is_returned'], name='library_loa_user_id_a71797_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['book', 'is_returned'], name='library_loa_book_id_8758ca_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrowed_date'], name='library_loa_borrowe_c019e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('user', 'book', 'borrowed_date')},
        ),
    ]
